// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {player} from '../models';

export function ChangeVolume(arg1:number):Promise<void>;

export function CurrentPosition():Promise<number>;

export function Init(arg1:context.Context):Promise<void>;

export function LoadFile(arg1:string):Promise<void>;

export function MuteToggle():Promise<void>;

export function Pause():Promise<void>;

export function Play():Promise<void>;

export function Resume():Promise<void>;

export function Seek(arg1:number):Promise<void>;

export function SetVolume(arg1:player.UserVolume):Promise<void>;

export function TrackLengthInSeconds():Promise<number>;
