// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {player} from '../models';
import {context} from '../models';
import {mediacontrols} from '../models';

export function ChangeVolume(arg1:number):Promise<void>;

export function CurrentPosition():Promise<number>;

export function CurrentPositionSeconds():Promise<number>;

export function EmitCurrentState():Promise<void>;

export function GetCurrentTrackInfo():Promise<player.TrackInfo>;

export function InitSpeaker():Promise<void>;

export function IsPlaying():Promise<boolean>;

export function LoadFile(arg1:string):Promise<void>;

export function MuteToggle():Promise<void>;

export function Pause():Promise<void>;

export function Play():Promise<void>;

export function RestoreState():Promise<void>;

export function SaveState():Promise<void>;

export function Seek(arg1:number):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetMediaControls(arg1:mediacontrols.Handler):Promise<void>;

export function SetPlaybackFinishedHandler(arg1:any):Promise<void>;

export function SetVolume(arg1:player.UserVolume):Promise<void>;

export function TrackLengthInSeconds():Promise<number>;

export function UnloadTrack():Promise<void>;
