// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeVolume(arg1) {
  return window['go']['player']['Player']['ChangeVolume'](arg1);
}

export function CurrentPosition() {
  return window['go']['player']['Player']['CurrentPosition']();
}

export function CurrentPositionSeconds() {
  return window['go']['player']['Player']['CurrentPositionSeconds']();
}

export function EmitCurrentState() {
  return window['go']['player']['Player']['EmitCurrentState']();
}

export function GetCurrentTrackInfo() {
  return window['go']['player']['Player']['GetCurrentTrackInfo']();
}

export function InitSpeaker() {
  return window['go']['player']['Player']['InitSpeaker']();
}

export function IsPlaying() {
  return window['go']['player']['Player']['IsPlaying']();
}

export function LoadFile(arg1) {
  return window['go']['player']['Player']['LoadFile'](arg1);
}

export function MuteToggle() {
  return window['go']['player']['Player']['MuteToggle']();
}

export function Pause() {
  return window['go']['player']['Player']['Pause']();
}

export function Play() {
  return window['go']['player']['Player']['Play']();
}

export function RestoreState() {
  return window['go']['player']['Player']['RestoreState']();
}

export function SaveState() {
  return window['go']['player']['Player']['SaveState']();
}

export function Seek(arg1) {
  return window['go']['player']['Player']['Seek'](arg1);
}

export function SetContext(arg1) {
  return window['go']['player']['Player']['SetContext'](arg1);
}

export function SetMediaControls(arg1) {
  return window['go']['player']['Player']['SetMediaControls'](arg1);
}

export function SetPlaybackFinishedHandler(arg1) {
  return window['go']['player']['Player']['SetPlaybackFinishedHandler'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['player']['Player']['SetVolume'](arg1);
}

export function TrackLengthInSeconds() {
  return window['go']['player']['Player']['TrackLengthInSeconds']();
}

export function UnloadTrack() {
  return window['go']['player']['Player']['UnloadTrack']();
}
