// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {queue} from '../models';
import {context} from '../models';

export function AddTrack(arg1:string):Promise<void>;

export function AddTracks(arg1:Array<string>):Promise<void>;

export function Clear():Promise<void>;

export function CycleRepeat():Promise<void>;

export function EmitCurrentState():Promise<void>;

export function GetState():Promise<queue.State>;

export function InsertNext(arg1:string):Promise<void>;

export function InsertNextTracks(arg1:Array<string>):Promise<void>;

export function InsertTracksAt(arg1:Array<string>,arg2:number):Promise<void>;

export function MoveQueueTracks(arg1:Array<number>,arg2:number):Promise<void>;

export function Next():Promise<void>;

export function OnPlaybackFinished():Promise<void>;

export function Play():Promise<void>;

export function PlayIndex(arg1:number):Promise<void>;

export function Previous():Promise<void>;

export function RemoveTrack(arg1:number):Promise<void>;

export function RemoveTracks(arg1:Array<number>):Promise<void>;

export function RestoreState():Promise<void>;

export function SaveState():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetPlayer(arg1:queue.TrackLoader):Promise<void>;

export function SetQueue(arg1:Array<string>,arg2:number,arg3:boolean):Promise<void>;

export function ToggleShuffle():Promise<void>;
