// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTrack(arg1) {
  return window['go']['queue']['Queue']['AddTrack'](arg1);
}

export function AddTracks(arg1) {
  return window['go']['queue']['Queue']['AddTracks'](arg1);
}

export function Clear() {
  return window['go']['queue']['Queue']['Clear']();
}

export function CompactAfterLibraryRemoval() {
  return window['go']['queue']['Queue']['CompactAfterLibraryRemoval']();
}

export function CycleRepeat() {
  return window['go']['queue']['Queue']['CycleRepeat']();
}

export function EmitCurrentState() {
  return window['go']['queue']['Queue']['EmitCurrentState']();
}

export function GetState() {
  return window['go']['queue']['Queue']['GetState']();
}

export function InsertNext(arg1) {
  return window['go']['queue']['Queue']['InsertNext'](arg1);
}

export function InsertNextTracks(arg1) {
  return window['go']['queue']['Queue']['InsertNextTracks'](arg1);
}

export function InsertTracksAt(arg1, arg2) {
  return window['go']['queue']['Queue']['InsertTracksAt'](arg1, arg2);
}

export function MoveQueueTracks(arg1, arg2) {
  return window['go']['queue']['Queue']['MoveQueueTracks'](arg1, arg2);
}

export function Next() {
  return window['go']['queue']['Queue']['Next']();
}

export function OnPlaybackFinished() {
  return window['go']['queue']['Queue']['OnPlaybackFinished']();
}

export function Play() {
  return window['go']['queue']['Queue']['Play']();
}

export function PlayIndex(arg1) {
  return window['go']['queue']['Queue']['PlayIndex'](arg1);
}

export function Previous() {
  return window['go']['queue']['Queue']['Previous']();
}

export function RemoveTrack(arg1) {
  return window['go']['queue']['Queue']['RemoveTrack'](arg1);
}

export function RemoveTracks(arg1) {
  return window['go']['queue']['Queue']['RemoveTracks'](arg1);
}

export function RestoreState() {
  return window['go']['queue']['Queue']['RestoreState']();
}

export function SaveState() {
  return window['go']['queue']['Queue']['SaveState']();
}

export function SetContext(arg1) {
  return window['go']['queue']['Queue']['SetContext'](arg1);
}

export function SetPlayer(arg1) {
  return window['go']['queue']['Queue']['SetPlayer'](arg1);
}

export function SetQueue(arg1, arg2, arg3) {
  return window['go']['queue']['Queue']['SetQueue'](arg1, arg2, arg3);
}

export function ToggleShuffle() {
  return window['go']['queue']['Queue']['ToggleShuffle']();
}
