// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DirectoryPicker() {
  return window['go']['frontendbindings']['FrontendBindings']['DirectoryPicker']();
}

export function Init(arg1) {
  return window['go']['frontendbindings']['FrontendBindings']['Init'](arg1);
}
