// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// -- Explore types (inline, matching Go JSON tags) ------------------

export interface MBArtist {
  mbid: string;
  name: string;
  sortName: string;
  type: string;
  country: string;
  disambiguation: string;
  score: number;
}

export interface MBReleaseGroup {
  mbid: string;
  title: string;
  primaryType: string;
  secondaryTypes?: string[];
  firstReleaseDate: string;
  artistCredit: string;
}

export interface MBRecording {
  mbid: string;
  title: string;
  length: number;
  artistCredit: string;
  score: number;
}

export interface MBRelease {
  mbid: string;
  title: string;
  date: string;
  country: string;
  status: string;
  tracks?: MBTrack[];
}

export interface MBTrack {
  position: number;
  title: string;
  length: number;
  mbid: string;
}

export interface MBSearchResult {
  artists?: MBArtist[];
  releaseGroups?: MBReleaseGroup[];
  recordings?: MBRecording[];
}

export interface LBTopRecording {
  recordingMbid: string;
  artistName: string;
  trackName: string;
  totalListenCount: number;
}

export interface LBSimilarArtist {
  artistMbid: string;
  name: string;
  score: number;
}

// -- Service methods ------------------------------------------------

export function Search(arg1:string):Promise<MBSearchResult>;

export function SearchArtists(arg1:string):Promise<Array<MBArtist>>;

export function SearchReleaseGroups(arg1:string):Promise<Array<MBReleaseGroup>>;

export function SearchRecordings(arg1:string):Promise<Array<MBRecording>>;

export function LookupArtist(arg1:string):Promise<MBArtist>;

export function LookupReleaseGroup(arg1:string):Promise<MBReleaseGroup>;

export function BrowseReleaseGroups(arg1:string):Promise<Array<MBReleaseGroup>>;

export function BrowseReleases(arg1:string):Promise<Array<MBRelease>>;

export function TopRecordingsForArtist(arg1:string):Promise<Array<LBTopRecording>>;

export function SimilarArtists(arg1:string):Promise<Array<LBSimilarArtist>>;

export function CoverArtURL(arg1:string):Promise<string>;

export function CoverArtGroupURL(arg1:string):Promise<string>;
