// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseReleaseGroups(arg1) {
  return window['go']['explore']['Service']['BrowseReleaseGroups'](arg1);
}

export function BrowseReleases(arg1) {
  return window['go']['explore']['Service']['BrowseReleases'](arg1);
}

export function CheckLibraryMBIDs(arg1) {
  return window['go']['explore']['Service']['CheckLibraryMBIDs'](arg1);
}

export function CoverArtGroupURL(arg1) {
  return window['go']['explore']['Service']['CoverArtGroupURL'](arg1);
}

export function CoverArtURL(arg1) {
  return window['go']['explore']['Service']['CoverArtURL'](arg1);
}

export function GetArtistImageCached(arg1) {
  return window['go']['explore']['Service']['GetArtistImageCached'](arg1);
}

export function GetArtistImageCachedPath(arg1) {
  return window['go']['explore']['Service']['GetArtistImageCachedPath'](arg1);
}

export function GetArtistImageURL(arg1) {
  return window['go']['explore']['Service']['GetArtistImageURL'](arg1);
}

export function GetArtistImages(arg1) {
  return window['go']['explore']['Service']['GetArtistImages'](arg1);
}

export function GetArtistMBID(arg1) {
  return window['go']['explore']['Service']['GetArtistMBID'](arg1);
}

export function GetArtistPlayCount(arg1) {
  return window['go']['explore']['Service']['GetArtistPlayCount'](arg1);
}

export function GetIndexStatus() {
  return window['go']['explore']['Service']['GetIndexStatus']();
}

export function GetLibrarySimilarArtists(arg1) {
  return window['go']['explore']['Service']['GetLibrarySimilarArtists'](arg1);
}

export function GetPopularityBatch(arg1) {
  return window['go']['explore']['Service']['GetPopularityBatch'](arg1);
}

export function GetThumbnail(arg1, arg2, arg3) {
  return window['go']['explore']['Service']['GetThumbnail'](arg1, arg2, arg3);
}

export function GetThumbnails(arg1) {
  return window['go']['explore']['Service']['GetThumbnails'](arg1);
}

export function GetTrackThumbnail(arg1, arg2, arg3, arg4) {
  return window['go']['explore']['Service']['GetTrackThumbnail'](arg1, arg2, arg3, arg4);
}

export function GetTrackThumbnails(arg1) {
  return window['go']['explore']['Service']['GetTrackThumbnails'](arg1);
}

export function IndexNewArtists() {
  return window['go']['explore']['Service']['IndexNewArtists']();
}

export function InvalidateIndexDiscographies() {
  return window['go']['explore']['Service']['InvalidateIndexDiscographies']();
}

export function IsIndexReady() {
  return window['go']['explore']['Service']['IsIndexReady']();
}

export function LookupArtist(arg1) {
  return window['go']['explore']['Service']['LookupArtist'](arg1);
}

export function LookupReleaseGroup(arg1) {
  return window['go']['explore']['Service']['LookupReleaseGroup'](arg1);
}

export function PopulateLocalCrossReferences() {
  return window['go']['explore']['Service']['PopulateLocalCrossReferences']();
}

export function RecordSearchClick(arg1, arg2, arg3) {
  return window['go']['explore']['Service']['RecordSearchClick'](arg1, arg2, arg3);
}

export function ResolveReleaseGroupMBIDs(arg1) {
  return window['go']['explore']['Service']['ResolveReleaseGroupMBIDs'](arg1);
}

export function Search(arg1) {
  return window['go']['explore']['Service']['Search'](arg1);
}

export function SearchArtists(arg1) {
  return window['go']['explore']['Service']['SearchArtists'](arg1);
}

export function SearchLocal(arg1) {
  return window['go']['explore']['Service']['SearchLocal'](arg1);
}

export function SearchRecordings(arg1) {
  return window['go']['explore']['Service']['SearchRecordings'](arg1);
}

export function SearchReleaseGroups(arg1) {
  return window['go']['explore']['Service']['SearchReleaseGroups'](arg1);
}

export function SetContext(arg1) {
  return window['go']['explore']['Service']['SetContext'](arg1);
}

export function SimilarArtists(arg1) {
  return window['go']['explore']['Service']['SimilarArtists'](arg1);
}

export function StartIndexBuild() {
  return window['go']['explore']['Service']['StartIndexBuild']();
}

export function StopIndexBuild() {
  return window['go']['explore']['Service']['StopIndexBuild']();
}

export function TopRecordingsForArtist(arg1) {
  return window['go']['explore']['Service']['TopRecordingsForArtist'](arg1);
}

export function TopReleaseGroupsForArtist(arg1) {
  return window['go']['explore']['Service']['TopReleaseGroupsForArtist'](arg1);
}

export function WaitForIndexIdle() {
  return window['go']['explore']['Service']['WaitForIndexIdle']();
}
