// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToDefaultPlaylist(arg1) {
  return window['go']['playlist']['Service']['AddToDefaultPlaylist'](arg1);
}

export function AddTracksToPlaylist(arg1, arg2) {
  return window['go']['playlist']['Service']['AddTracksToPlaylist'](arg1, arg2);
}

export function CreatePlaylist(arg1) {
  return window['go']['playlist']['Service']['CreatePlaylist'](arg1);
}

export function CreatePlaylistWithTracks(arg1, arg2) {
  return window['go']['playlist']['Service']['CreatePlaylistWithTracks'](arg1, arg2);
}

export function DeletePlaylist(arg1) {
  return window['go']['playlist']['Service']['DeletePlaylist'](arg1);
}

export function EnsureDefaultPlaylist() {
  return window['go']['playlist']['Service']['EnsureDefaultPlaylist']();
}

export function FindPhantomMatches(arg1, arg2) {
  return window['go']['playlist']['Service']['FindPhantomMatches'](arg1, arg2);
}

export function GetAllPlaylists() {
  return window['go']['playlist']['Service']['GetAllPlaylists']();
}

export function GetAllPlaylistsWithTracks() {
  return window['go']['playlist']['Service']['GetAllPlaylistsWithTracks']();
}

export function GetDefaultPlaylistInfo() {
  return window['go']['playlist']['Service']['GetDefaultPlaylistInfo']();
}

export function GetDefaultPlaylistTrackPaths() {
  return window['go']['playlist']['Service']['GetDefaultPlaylistTrackPaths']();
}

export function GetPhantomCandidates(arg1, arg2) {
  return window['go']['playlist']['Service']['GetPhantomCandidates'](arg1, arg2);
}

export function GetPlaylistTracks(arg1) {
  return window['go']['playlist']['Service']['GetPlaylistTracks'](arg1);
}

export function ImportPlaylist(arg1) {
  return window['go']['playlist']['Service']['ImportPlaylist'](arg1);
}

export function RemoveFromDefaultPlaylist(arg1) {
  return window['go']['playlist']['Service']['RemoveFromDefaultPlaylist'](arg1);
}

export function RemovePhantomTracks(arg1, arg2) {
  return window['go']['playlist']['Service']['RemovePhantomTracks'](arg1, arg2);
}

export function RemoveTracksFromPlaylist(arg1, arg2) {
  return window['go']['playlist']['Service']['RemoveTracksFromPlaylist'](arg1, arg2);
}

export function RenamePlaylist(arg1, arg2) {
  return window['go']['playlist']['Service']['RenamePlaylist'](arg1, arg2);
}

export function ResolvePhantomTracks(arg1, arg2) {
  return window['go']['playlist']['Service']['ResolvePhantomTracks'](arg1, arg2);
}

export function RestoreAllPlaylists() {
  return window['go']['playlist']['Service']['RestoreAllPlaylists']();
}

export function SearchLibrary(arg1) {
  return window['go']['playlist']['Service']['SearchLibrary'](arg1);
}

export function SetContext(arg1) {
  return window['go']['playlist']['Service']['SetContext'](arg1);
}

export function SetFavoritesConfig(arg1) {
  return window['go']['playlist']['Service']['SetFavoritesConfig'](arg1);
}

export function ToggleDefaultPlaylistTrack(arg1) {
  return window['go']['playlist']['Service']['ToggleDefaultPlaylistTrack'](arg1);
}
