// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTracksToPlaylist(arg1, arg2) {
  return window['go']['playlist']['Service']['AddTracksToPlaylist'](arg1, arg2);
}

export function CreatePlaylist(arg1) {
  return window['go']['playlist']['Service']['CreatePlaylist'](arg1);
}

export function CreatePlaylistWithTracks(arg1, arg2) {
  return window['go']['playlist']['Service']['CreatePlaylistWithTracks'](arg1, arg2);
}

export function GetAllPlaylists() {
  return window['go']['playlist']['Service']['GetAllPlaylists']();
}

export function GetPlaylistTracks(arg1) {
  return window['go']['playlist']['Service']['GetPlaylistTracks'](arg1);
}

export function SetContext(arg1) {
  return window['go']['playlist']['Service']['SetContext'](arg1);
}
