// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {playlist} from '../models';
import {context} from '../models';

export function AddTracksToPlaylist(arg1:number,arg2:Array<string>):Promise<void>;

export function CreatePlaylist(arg1:string):Promise<playlist.Summary>;

export function CreatePlaylistWithTracks(arg1:string,arg2:Array<string>):Promise<playlist.Summary>;

export function GetAllPlaylists():Promise<Array<playlist.Summary>>;

export function GetAllPlaylistsWithTracks():Promise<Array<playlist.WithTracks>>;

export function GetPlaylistTracks(arg1:number):Promise<Array<playlist.Track>>;

export function RemoveTracksFromPlaylist(arg1:number,arg2:Array<number>):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
