// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {jobs} from '../models';

export function CancelJob(arg1:string):Promise<void>;

export function ClearFinishedJobs():Promise<void>;

export function DismissJob(arg1:string):Promise<void>;

export function GetJobLog(arg1:string):Promise<Array<jobs.LogEntry>>;

export function GetJobs():Promise<Array<jobs.Job>>;

export function PauseJob(arg1:string):Promise<void>;

export function ResumeJob(arg1:string):Promise<void>;
