// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BatchFailure records a single track that failed during a batch write.
 */
export interface BatchFailure {
    "filePath": string;
    "error": string;
}

/**
 * BatchResult summarises the outcome of a batch tag write.
 */
export interface BatchResult {
    "total": number;
    "succeeded": number;
    "failed": number;
    "cancelled": boolean;
    "failures": BatchFailure[] | null;
}

/**
 * TagChanges is a diff map of field name → new value. Only changed
 * fields are present. Callers specify changed fields; unchanged
 * fields are left as-is in the file.
 */
export type TagChanges = { [_ in string]?: any } | null;
