// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artist_credit_artists.sql

package sqlcgen

import (
	"context"
)

const createArtistCreditArtist = `-- name: CreateArtistCreditArtist :one
INSERT INTO artist_credit_artist (artist_id, credit_id) VALUES (?, ?)
RETURNING id, artist_id, credit_id
`

type CreateArtistCreditArtistParams struct {
	ArtistID int64
	CreditID int64
}

func (q *Queries) CreateArtistCreditArtist(ctx context.Context, arg CreateArtistCreditArtistParams) (ArtistCreditArtist, error) {
	row := q.db.QueryRowContext(ctx, createArtistCreditArtist, arg.ArtistID, arg.CreditID)
	var i ArtistCreditArtist
	err := row.Scan(&i.ID, &i.ArtistID, &i.CreditID)
	return i, err
}

const deleteAllArtistCreditArtists = `-- name: DeleteAllArtistCreditArtists :exec
DELETE FROM artist_credit_artist
`

func (q *Queries) DeleteAllArtistCreditArtists(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllArtistCreditArtists)
	return err
}

const deleteArtistCreditArtist = `-- name: DeleteArtistCreditArtist :exec
DELETE FROM artist_credit_artist 
WHERE id =?
`

func (q *Queries) DeleteArtistCreditArtist(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteArtistCreditArtist, id)
	return err
}

const getArtistCreditArtist = `-- name: GetArtistCreditArtist :one
SELECT id, artist_id, credit_id FROM artist_credit_artist 
WHERE id = ? LIMIT 1
`

func (q *Queries) GetArtistCreditArtist(ctx context.Context, id int64) (ArtistCreditArtist, error) {
	row := q.db.QueryRowContext(ctx, getArtistCreditArtist, id)
	var i ArtistCreditArtist
	err := row.Scan(&i.ID, &i.ArtistID, &i.CreditID)
	return i, err
}

const updateArtistCreditArtist = `-- name: UpdateArtistCreditArtist :exec
UPDATE artist_credit_artist 
SET artist_id = ?, credit_id = ?
WHERE id =?
`

type UpdateArtistCreditArtistParams struct {
	ArtistID int64
	CreditID int64
	ID       int64
}

func (q *Queries) UpdateArtistCreditArtist(ctx context.Context, arg UpdateArtistCreditArtistParams) error {
	_, err := q.db.ExecContext(ctx, updateArtistCreditArtist, arg.ArtistID, arg.CreditID, arg.ID)
	return err
}
