// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artist_credit.sql

package sqlcgen

import (
	"context"
)

const countArtistCreditReferences = `-- name: CountArtistCreditReferences :one
SELECT
  (SELECT COUNT(*) FROM recordings WHERE artist_credit_id = ?1) +
  (SELECT COUNT(*) FROM release_groups WHERE album_artist_credit_id = ?1)
AS total
`

func (q *Queries) CountArtistCreditReferences(ctx context.Context, artistCreditID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArtistCreditReferences, artistCreditID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createArtistCredit = `-- name: CreateArtistCredit :one
INSERT INTO artist_credit (text) VALUES (?)
RETURNING id, text
`

func (q *Queries) CreateArtistCredit(ctx context.Context, text string) (ArtistCredit, error) {
	row := q.db.QueryRowContext(ctx, createArtistCredit, text)
	var i ArtistCredit
	err := row.Scan(&i.ID, &i.Text)
	return i, err
}

const deleteAllArtistCredits = `-- name: DeleteAllArtistCredits :exec
DELETE FROM artist_credit
`

func (q *Queries) DeleteAllArtistCredits(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllArtistCredits)
	return err
}

const deleteArtistCredit = `-- name: DeleteArtistCredit :exec
DELETE FROM artist_credit 
WHERE id = ?
`

func (q *Queries) DeleteArtistCredit(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteArtistCredit, id)
	return err
}

const getArtistCredit = `-- name: GetArtistCredit :one
SELECT id, text FROM artist_credit 
WHERE id = ? LIMIT 1
`

func (q *Queries) GetArtistCredit(ctx context.Context, id int64) (ArtistCredit, error) {
	row := q.db.QueryRowContext(ctx, getArtistCredit, id)
	var i ArtistCredit
	err := row.Scan(&i.ID, &i.Text)
	return i, err
}

const getArtistCreditByText = `-- name: GetArtistCreditByText :one
SELECT id, text FROM artist_credit
WHERE text = ? LIMIT 1
`

func (q *Queries) GetArtistCreditByText(ctx context.Context, text string) (ArtistCredit, error) {
	row := q.db.QueryRowContext(ctx, getArtistCreditByText, text)
	var i ArtistCredit
	err := row.Scan(&i.ID, &i.Text)
	return i, err
}

const getOrphanedArtistCreditIDs = `-- name: GetOrphanedArtistCreditIDs :many
SELECT ac.id FROM artist_credit ac
WHERE NOT EXISTS (SELECT 1 FROM recordings r WHERE r.artist_credit_id = ac.id)
  AND NOT EXISTS (SELECT 1 FROM release_groups rg WHERE rg.album_artist_credit_id = ac.id)
`

// Artist credits no longer used by any recording or release group - run
// after orphaned recordings/release groups are deleted, so a credit
// that only existed for now-removed tracks is cleaned up too.
func (q *Queries) GetOrphanedArtistCreditIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getOrphanedArtistCreditIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtistCredit = `-- name: UpdateArtistCredit :exec
UPDATE artist_credit 
SET text = ?
WHERE id = ?
`

type UpdateArtistCreditParams struct {
	Text string
	ID   int64
}

func (q *Queries) UpdateArtistCredit(ctx context.Context, arg UpdateArtistCreditParams) error {
	_, err := q.db.ExecContext(ctx, updateArtistCredit, arg.Text, arg.ID)
	return err
}

const upsertArtistCredit = `-- name: UpsertArtistCredit :one
INSERT INTO artist_credit (text) VALUES (?)
ON CONFLICT(text) DO UPDATE SET text = excluded.text
RETURNING id, text
`

func (q *Queries) UpsertArtistCredit(ctx context.Context, text string) (ArtistCredit, error) {
	row := q.db.QueryRowContext(ctx, upsertArtistCredit, text)
	var i ArtistCredit
	err := row.Scan(&i.ID, &i.Text)
	return i, err
}
