// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artists.sql

package sqlcgen

import (
	"context"
)

const createArtist = `-- name: CreateArtist :one
INSERT INTO artists (name) VALUES (?)
RETURNING id, name
`

func (q *Queries) CreateArtist(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRowContext(ctx, createArtist, name)
	var i Artist
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteArtist = `-- name: DeleteArtist :exec
DELETE FROM artists 
WHERE id = ?
`

func (q *Queries) DeleteArtist(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteArtist, id)
	return err
}

const getAllArtists = `-- name: GetAllArtists :many
SELECT id, name FROM artists
ORDER BY name
`

func (q *Queries) GetAllArtists(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.QueryContext(ctx, getAllArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtist = `-- name: GetArtist :one
SELECT id, name FROM artists 
WHERE id = ? LIMIT 1
`

func (q *Queries) GetArtist(ctx context.Context, id int64) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtist, id)
	var i Artist
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getArtistByName = `-- name: GetArtistByName :one
SELECT id, name FROM artists
WHERE name = ? LIMIT 1
`

func (q *Queries) GetArtistByName(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtistByName, name)
	var i Artist
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const updateArtist = `-- name: UpdateArtist :exec
UPDATE artists 
SET name = ?
WHERE id = ?
`

type UpdateArtistParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateArtist(ctx context.Context, arg UpdateArtistParams) error {
	_, err := q.db.ExecContext(ctx, updateArtist, arg.Name, arg.ID)
	return err
}

const upsertArtist = `-- name: UpsertArtist :one
INSERT INTO artists (name) VALUES (?)
ON CONFLICT(name) DO UPDATE SET name = excluded.name
RETURNING id, name
`

func (q *Queries) UpsertArtist(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRowContext(ctx, upsertArtist, name)
	var i Artist
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
