// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

type Artist struct {
	ID   int64
	Name string
}

type ArtistCredit struct {
	ID   int64
	Text interface{}
}

type ArtistCreditArtist struct {
	ID int64
}

type AudioFile struct {
	ID                 int64
	FilePath           string
	LengthMilliseconds int64
}

type CoverArt struct {
	ID         int64
	IsEmbedded bool
	FilePath   string
}

type FileType struct {
	ID        int64
	Extension string
}

type Recording struct {
	ID   int64
	Name string
}

type ReleaseGroup struct {
	ID   int64
	Name string
}

type ReleaseGroupRecording struct {
	ID int64
}
