// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"time"
)

type Artist struct {
	ID   int64
	Name string
}

type ArtistCredit struct {
	ID   int64
	Text string
}

type ArtistCreditArtist struct {
	ID       int64
	ArtistID int64
	CreditID int64
}

type AudioFile struct {
	ID                 int64
	FilePath           string
	LengthMilliseconds int64
	FileTypeID         int64
	RecordingID        int64
}

type CoverArt struct {
	ID         int64
	IsEmbedded bool
	FilePath   string
	MimeType   string
}

type FileType struct {
	ID        int64
	Extension string
}

type PlayerState struct {
	ID                  int64
	Volume              int64
	Muted               bool
	LastTrackPath       string
	LastPositionSeconds int64
}

type Playlist struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PlaylistTrack struct {
	ID          int64
	PlaylistID  int64
	AudioFileID int64
	Position    int64
}

type Queue struct {
	ID               int64
	SourcePlaylistID sql.NullInt64
	CurrentPosition  int64
	ShuffleMode      bool
	RepeatMode       string
	ShuffleOrder     sql.NullString
}

type QueueTrack struct {
	ID          int64
	AudioFileID int64
	Position    int64
}

type Recording struct {
	ID             int64
	Name           string
	ArtistCreditID int64
	TrackNumber    sql.NullInt64
	DiscNumber     sql.NullInt64
	Year           sql.NullInt64
	Genre          sql.NullString
	Composer       sql.NullString
	Lyrics         sql.NullString
	Comment        sql.NullString
}

type ReleaseGroup struct {
	ID                  int64
	Name                string
	CoverArtID          sql.NullInt64
	AlbumArtistCreditID sql.NullInt64
	Year                sql.NullInt64
	TotalTracks         sql.NullInt64
	TotalDiscs          sql.NullInt64
}

type ReleaseGroupRecording struct {
	ID             int64
	ReleaseGroupID int64
	RecordingID    int64
	TrackNumber    sql.NullInt64
	DiscNumber     sql.NullInt64
}
