// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"time"
)

type Artist struct {
	ID   int64
	Name string
	Mbid sql.NullString
}

type ArtistCredit struct {
	ID   int64
	Text string
}

type ArtistCreditArtist struct {
	ID       int64
	ArtistID int64
	CreditID int64
}

type ArtistMetadatum struct {
	Mbid      string
	Source    string
	Data      []byte
	FetchedAt time.Time
}

type AudioFile struct {
	ID                 int64
	FilePath           string
	LengthMilliseconds int64
	FileTypeID         int64
	RecordingID        int64
	SampleRate         int64
	BitDepth           int64
	Channels           int64
	Bitrate            int64
	FileSize           int64
	Basename           string
	LibraryID          int64
	PlayCount          int64
	LastPlayed         sql.NullTime
	TagStatus          string
	GroupKey           string
}

type CoverArt struct {
	ID         int64
	IsEmbedded bool
	FilePath   string
	MimeType   string
}

type FileType struct {
	ID        int64
	Extension string
}

type Genre struct {
	ID   int64
	Name string
}

type HttpCache struct {
	UrlKey     string
	Response   []byte
	ExpiresAt  time.Time
	EntityMbid string
	EntityType string
}

type JobState struct {
	ID       string
	Kind     string
	Title    string
	Subtitle string
	PausedAt string
}

type Library struct {
	ID                  int64
	Name                string
	Path                string
	CreatedAt           time.Time
	AutotagWarningAcked int64
}

type LyricsIndex struct {
	Lyrics string
}

type PlayHistory struct {
	ID          int64
	AudioFileID int64
	PlayedAt    time.Time
}

type PlayerState struct {
	ID                  int64
	Volume              int64
	Muted               bool
	LastTrackPath       string
	LastPositionSeconds int64
}

type Playlist struct {
	ID              int64
	Name            string
	IsSmart         int64
	SmartRules      sql.NullString
	SmartSnapshotAt sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type PlaylistTrack struct {
	ID                  int64
	PlaylistID          int64
	AudioFileID         sql.NullInt64
	Position            int64
	PhantomTitle        sql.NullString
	PhantomArtist       sql.NullString
	PhantomAlbum        sql.NullString
	PhantomDurationMs   sql.NullInt64
	PhantomGenre        sql.NullString
	PhantomCoverArtPath sql.NullString
	PhantomFilePath     sql.NullString
}

type Queue struct {
	ID               int64
	SourcePlaylistID sql.NullInt64
	CurrentPosition  int64
	ShuffleMode      bool
	RepeatMode       string
	ShuffleOrder     sql.NullString
}

type QueueTrack struct {
	ID          int64
	AudioFileID int64
	Position    int64
}

type Recording struct {
	ID             int64
	Name           string
	ArtistCreditID int64
	TrackNumber    sql.NullInt64
	DiscNumber     sql.NullInt64
	Year           sql.NullInt64
	Genre          sql.NullString
	Composer       sql.NullString
	Lyrics         sql.NullString
	Comment        sql.NullString
	Mbid           sql.NullString
}

type RecordingGenre struct {
	ID          int64
	RecordingID int64
	GenreID     int64
}

type ReleaseGroup struct {
	ID                  int64
	Name                string
	CoverArtID          sql.NullInt64
	AlbumArtistCreditID sql.NullInt64
	Year                sql.NullInt64
	OriginalYear        sql.NullInt64
	TotalTracks         sql.NullInt64
	TotalDiscs          sql.NullInt64
	Mbid                sql.NullString
}

type ReleaseGroupRecording struct {
	ID             int64
	ReleaseGroupID int64
	RecordingID    int64
	TrackNumber    sql.NullInt64
	DiscNumber     sql.NullInt64
}

type SearchIndex struct {
	FilePath string
	Title    string
	Artist   string
	Album    string
}

type TaggingCandidate struct {
	GroupKey   string
	Candidates string
	ComputedAt time.Time
}

type TaggingItem struct {
	GroupKey             string
	LibraryID            int64
	TrackCount           int64
	AlbumName            string
	AlbumArtist          string
	DiscNumber           int64
	BestMatchReleaseMbid sql.NullString
	Score                sql.NullFloat64
	LastCheckedAt        sql.NullTime
	Status               string
	ClearedAt            sql.NullTime
	CreatedAt            time.Time
}

type TrackMetadatum struct {
	ID                 int64
	FilePath           string
	LengthMilliseconds int64
	Title              string
	ArtistName         string
	TrackNumber        sql.NullInt64
	DiscNumber         sql.NullInt64
	Album              string
	Genre              string
	Year               int64
	ReleaseYear        int64
	Composer           string
	FileType           string
	SampleRate         int64
	BitDepth           int64
	Channels           int64
	Bitrate            int64
	FileSize           int64
	LibraryID          int64
	PlayCount          int64
	LastPlayed         sql.NullTime
	CoverArtPath       string
	ArtistMbid         string
	ReleaseGroupMbid   string
	RecordingMbid      string
}
