// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: release_groups.sql

package sqlcgen

import (
	"context"
)

const createReleaseGroup = `-- name: CreateReleaseGroup :one
INSERT INTO release_groups (name) VALUES (?)
RETURNING id, name, cover_art_id
`

func (q *Queries) CreateReleaseGroup(ctx context.Context, name string) (ReleaseGroup, error) {
	row := q.db.QueryRowContext(ctx, createReleaseGroup, name)
	var i ReleaseGroup
	err := row.Scan(&i.ID, &i.Name, &i.CoverArtID)
	return i, err
}

const deleteReleaseGroup = `-- name: DeleteReleaseGroup :exec
DELETE FROM release_groups 
WHERE id =?
`

func (q *Queries) DeleteReleaseGroup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReleaseGroup, id)
	return err
}

const getReleaseGroup = `-- name: GetReleaseGroup :one
SELECT id, name, cover_art_id FROM release_groups 
WHERE id = ? LIMIT 1
`

func (q *Queries) GetReleaseGroup(ctx context.Context, id int64) (ReleaseGroup, error) {
	row := q.db.QueryRowContext(ctx, getReleaseGroup, id)
	var i ReleaseGroup
	err := row.Scan(&i.ID, &i.Name, &i.CoverArtID)
	return i, err
}

const updateReleaseGroup = `-- name: UpdateReleaseGroup :exec
UPDATE release_groups 
SET name = ?
WHERE id =?
`

type UpdateReleaseGroupParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateReleaseGroup(ctx context.Context, arg UpdateReleaseGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateReleaseGroup, arg.Name, arg.ID)
	return err
}
