// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: release_group_recordings.sql

package sqlcgen

import (
	"context"
)

const createReleaseGroupRecording = `-- name: CreateReleaseGroupRecording :one
INSERT INTO release_group_recordings (release_group_id, recording_id) VALUES (?,?) 
RETURNING id, release_group_id, recording_id
`

type CreateReleaseGroupRecordingParams struct {
	ReleaseGroupID int64
	RecordingID    int64
}

func (q *Queries) CreateReleaseGroupRecording(ctx context.Context, arg CreateReleaseGroupRecordingParams) (ReleaseGroupRecording, error) {
	row := q.db.QueryRowContext(ctx, createReleaseGroupRecording, arg.ReleaseGroupID, arg.RecordingID)
	var i ReleaseGroupRecording
	err := row.Scan(&i.ID, &i.ReleaseGroupID, &i.RecordingID)
	return i, err
}

const deleteReleaseGroupRecording = `-- name: DeleteReleaseGroupRecording :exec
DELETE FROM release_group_recordings 
WHERE id =?
`

func (q *Queries) DeleteReleaseGroupRecording(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReleaseGroupRecording, id)
	return err
}

const getReleaseGroupRecording = `-- name: GetReleaseGroupRecording :one
SELECT id, release_group_id, recording_id FROM release_group_recordings 
WHERE id = ? LIMIT 1
`

func (q *Queries) GetReleaseGroupRecording(ctx context.Context, id int64) (ReleaseGroupRecording, error) {
	row := q.db.QueryRowContext(ctx, getReleaseGroupRecording, id)
	var i ReleaseGroupRecording
	err := row.Scan(&i.ID, &i.ReleaseGroupID, &i.RecordingID)
	return i, err
}

const updateReleaseGroupRecording = `-- name: UpdateReleaseGroupRecording :exec
UPDATE release_group_recordings 
SET release_group_id = ?, recording_id = ?
WHERE id =?
`

type UpdateReleaseGroupRecordingParams struct {
	ReleaseGroupID int64
	RecordingID    int64
	ID             int64
}

func (q *Queries) UpdateReleaseGroupRecording(ctx context.Context, arg UpdateReleaseGroupRecordingParams) error {
	_, err := q.db.ExecContext(ctx, updateReleaseGroupRecording, arg.ReleaseGroupID, arg.RecordingID, arg.ID)
	return err
}
