// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: release_group_recordings.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createReleaseGroupRecording = `-- name: CreateReleaseGroupRecording :one
INSERT INTO release_group_recordings (release_group_id, recording_id, track_number, disc_number)
VALUES (?, ?, ?, ?)
RETURNING id, release_group_id, recording_id, track_number, disc_number
`

type CreateReleaseGroupRecordingParams struct {
	ReleaseGroupID int64
	RecordingID    int64
	TrackNumber    sql.NullInt64
	DiscNumber     sql.NullInt64
}

func (q *Queries) CreateReleaseGroupRecording(ctx context.Context, arg CreateReleaseGroupRecordingParams) (ReleaseGroupRecording, error) {
	row := q.db.QueryRowContext(ctx, createReleaseGroupRecording,
		arg.ReleaseGroupID,
		arg.RecordingID,
		arg.TrackNumber,
		arg.DiscNumber,
	)
	var i ReleaseGroupRecording
	err := row.Scan(
		&i.ID,
		&i.ReleaseGroupID,
		&i.RecordingID,
		&i.TrackNumber,
		&i.DiscNumber,
	)
	return i, err
}

const deleteReleaseGroupRecording = `-- name: DeleteReleaseGroupRecording :exec
DELETE FROM release_group_recordings 
WHERE id = ?
`

func (q *Queries) DeleteReleaseGroupRecording(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReleaseGroupRecording, id)
	return err
}

const deleteReleaseGroupRecordingByFK = `-- name: DeleteReleaseGroupRecordingByFK :exec
DELETE FROM release_group_recordings
WHERE release_group_id = ? AND recording_id = ?
`

type DeleteReleaseGroupRecordingByFKParams struct {
	ReleaseGroupID int64
	RecordingID    int64
}

func (q *Queries) DeleteReleaseGroupRecordingByFK(ctx context.Context, arg DeleteReleaseGroupRecordingByFKParams) error {
	_, err := q.db.ExecContext(ctx, deleteReleaseGroupRecordingByFK, arg.ReleaseGroupID, arg.RecordingID)
	return err
}

const getRecordingReleaseGroups = `-- name: GetRecordingReleaseGroups :many
SELECT id, release_group_id, recording_id, track_number, disc_number FROM release_group_recordings
WHERE recording_id = ?
`

func (q *Queries) GetRecordingReleaseGroups(ctx context.Context, recordingID int64) ([]ReleaseGroupRecording, error) {
	rows, err := q.db.QueryContext(ctx, getRecordingReleaseGroups, recordingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReleaseGroupRecording
	for rows.Next() {
		var i ReleaseGroupRecording
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseGroupID,
			&i.RecordingID,
			&i.TrackNumber,
			&i.DiscNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReleaseGroupRecording = `-- name: GetReleaseGroupRecording :one
SELECT id, release_group_id, recording_id, track_number, disc_number FROM release_group_recordings 
WHERE id = ? LIMIT 1
`

func (q *Queries) GetReleaseGroupRecording(ctx context.Context, id int64) (ReleaseGroupRecording, error) {
	row := q.db.QueryRowContext(ctx, getReleaseGroupRecording, id)
	var i ReleaseGroupRecording
	err := row.Scan(
		&i.ID,
		&i.ReleaseGroupID,
		&i.RecordingID,
		&i.TrackNumber,
		&i.DiscNumber,
	)
	return i, err
}

const getReleaseGroupRecordings = `-- name: GetReleaseGroupRecordings :many
SELECT id, release_group_id, recording_id, track_number, disc_number FROM release_group_recordings
WHERE release_group_id = ?
ORDER BY disc_number, track_number
`

func (q *Queries) GetReleaseGroupRecordings(ctx context.Context, releaseGroupID int64) ([]ReleaseGroupRecording, error) {
	rows, err := q.db.QueryContext(ctx, getReleaseGroupRecordings, releaseGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReleaseGroupRecording
	for rows.Next() {
		var i ReleaseGroupRecording
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseGroupID,
			&i.RecordingID,
			&i.TrackNumber,
			&i.DiscNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
