// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service builds the home page's shelves.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetShelves returns the home page's rows, in display order.
 * 
 * It is a single call rather than one per shelf because the shelves
 * share an album lookup and because the page has nothing useful to
 * render until it knows which rows exist — a page that pops rows in one
 * at a time reflows under the user's cursor.
 */
export function GetShelves(): $CancellablePromise<$models.Shelf[] | null> {
    return $Call.ByID(2822423495);
}
