// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetContext(arg1) {
  return window['go']['tagwriter']['TagWriter']['SetContext'](arg1);
}

export function WriteTrackTags(arg1, arg2) {
  return window['go']['tagwriter']['TagWriter']['WriteTrackTags'](arg1, arg2);
}

export function WriteTrackTagsByPath(arg1, arg2) {
  return window['go']['tagwriter']['TagWriter']['WriteTrackTagsByPath'](arg1, arg2);
}
