// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tagwriter} from '../models';
import {context} from '../models';

export function BatchWriteTrackTags(arg1:Array<string>,arg2:tagwriter.TagChanges):Promise<tagwriter.BatchResult>;

export function CancelBatchWrite():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function WriteTrackTags(arg1:number,arg2:tagwriter.TagChanges):Promise<void>;

export function WriteTrackTagsByPath(arg1:string,arg2:tagwriter.TagChanges):Promise<void>;
