// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http} from '../models';
import {context} from '../models';

export function GetLibraryDirectory():Promise<string>;

export function GetScanConcurrency():Promise<string>;

export function Load():Promise<void>;

export function Save():Promise<void>;

export function ServeHTTP(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetLibraryDirectory(arg1:string):Promise<void>;

export function SetScanConcurrency(arg1:string):Promise<void>;

export function Validate():Promise<void>;
