// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLibraryDirectory() {
  return window['go']['config']['Config']['GetLibraryDirectory']();
}

export function GetScanConcurrency() {
  return window['go']['config']['Config']['GetScanConcurrency']();
}

export function Load() {
  return window['go']['config']['Config']['Load']();
}

export function Save() {
  return window['go']['config']['Config']['Save']();
}

export function ServeHTTP(arg1, arg2) {
  return window['go']['config']['Config']['ServeHTTP'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['config']['Config']['SetContext'](arg1);
}

export function SetLibraryDirectory(arg1) {
  return window['go']['config']['Config']['SetLibraryDirectory'](arg1);
}

export function SetScanConcurrency(arg1) {
  return window['go']['config']['Config']['SetScanConcurrency'](arg1);
}

export function Validate() {
  return window['go']['config']['Config']['Validate']();
}
