// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {download} from '../models';
import {tracklist} from '../models';
import {context} from '../models';

export function GetDownloadPreferences():Promise<download.AutoDownloadPrefs>;

export function GetFavoritesIconStyle():Promise<string>;

export function GetFavoritesPlaylistID():Promise<number>;

export function GetLibraryDirectory():Promise<string>;

export function GetPinDefaultPlaylist():Promise<boolean>;

export function GetScanConcurrency():Promise<string>;

export function GetShortcuts():Promise<Record<string, string>>;

export function GetThemeAccentColor():Promise<string>;

export function GetThemeBackgroundShade():Promise<string>;

export function GetTrackListColumns():Promise<Array<tracklist.Column>>;

export function Load():Promise<void>;

export function ResetShortcuts():Promise<void>;

export function Save():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetDownloadPreferences(arg1:download.AutoDownloadPrefs):Promise<void>;

export function SetFavoritesIconStyle(arg1:string):Promise<void>;

export function SetFavoritesPlaylistID(arg1:number):Promise<void>;

export function SetLibraryDirectory(arg1:string):Promise<void>;

export function SetPinDefaultPlaylist(arg1:boolean):Promise<void>;

export function SetScanConcurrency(arg1:string):Promise<void>;

export function SetShortcut(arg1:string,arg2:string):Promise<void>;

export function SetShortcuts(arg1:Record<string, string>):Promise<void>;

export function SetThemeAccentColor(arg1:string):Promise<void>;

export function SetThemeBackgroundShade(arg1:string):Promise<void>;

export function SetTrackListColumns(arg1:Array<tracklist.Column>):Promise<void>;

export function Validate():Promise<void>;
