// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFavoritesIconStyle() {
  return window['go']['config']['Config']['GetFavoritesIconStyle']();
}

export function GetFavoritesPlaylistID() {
  return window['go']['config']['Config']['GetFavoritesPlaylistID']();
}

export function GetLibraryDirectory() {
  return window['go']['config']['Config']['GetLibraryDirectory']();
}

export function GetPinDefaultPlaylist() {
  return window['go']['config']['Config']['GetPinDefaultPlaylist']();
}

export function GetScanConcurrency() {
  return window['go']['config']['Config']['GetScanConcurrency']();
}

export function GetShortcuts() {
  return window['go']['config']['Config']['GetShortcuts']();
}

export function GetThemeAccentColor() {
  return window['go']['config']['Config']['GetThemeAccentColor']();
}

export function GetThemeBackgroundShade() {
  return window['go']['config']['Config']['GetThemeBackgroundShade']();
}

export function GetTrackListColumns() {
  return window['go']['config']['Config']['GetTrackListColumns']();
}

export function Load() {
  return window['go']['config']['Config']['Load']();
}

export function ResetShortcuts() {
  return window['go']['config']['Config']['ResetShortcuts']();
}

export function Save() {
  return window['go']['config']['Config']['Save']();
}

export function SetContext(arg1) {
  return window['go']['config']['Config']['SetContext'](arg1);
}

export function SetFavoritesIconStyle(arg1) {
  return window['go']['config']['Config']['SetFavoritesIconStyle'](arg1);
}

export function SetFavoritesPlaylistID(arg1) {
  return window['go']['config']['Config']['SetFavoritesPlaylistID'](arg1);
}

export function SetLibraryDirectory(arg1) {
  return window['go']['config']['Config']['SetLibraryDirectory'](arg1);
}

export function SetPinDefaultPlaylist(arg1) {
  return window['go']['config']['Config']['SetPinDefaultPlaylist'](arg1);
}

export function SetScanConcurrency(arg1) {
  return window['go']['config']['Config']['SetScanConcurrency'](arg1);
}

export function SetShortcut(arg1, arg2) {
  return window['go']['config']['Config']['SetShortcut'](arg1, arg2);
}

export function SetShortcuts(arg1) {
  return window['go']['config']['Config']['SetShortcuts'](arg1);
}

export function SetThemeAccentColor(arg1) {
  return window['go']['config']['Config']['SetThemeAccentColor'](arg1);
}

export function SetThemeBackgroundShade(arg1) {
  return window['go']['config']['Config']['SetThemeBackgroundShade'](arg1);
}

export function SetTrackListColumns(arg1) {
  return window['go']['config']['Config']['SetTrackListColumns'](arg1);
}

export function Validate() {
  return window['go']['config']['Config']['Validate']();
}
