// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {download} from '../models';
import {context} from '../models';

export function AddProvider(arg1:string,arg2:string,arg3:Record<string, string>):Promise<number>;

export function AddRequest(arg1:download.RequestInput):Promise<number>;

export function Cancel(arg1:string):Promise<void>;

export function Candidates(arg1:string):Promise<Array<download.Candidate>>;

export function ClearFinished():Promise<void>;

export function ClearSatisfiedRequests():Promise<void>;

export function DeleteProvider(arg1:number):Promise<void>;

export function ImportExternalRequests(arg1:number,arg2:number):Promise<number>;

export function IsRequested(arg1:string,arg2:number):Promise<boolean>;

export function ListDownloads(arg1:number):Promise<Array<download.DownloadView>>;

export function ListProviders():Promise<Array<download.Config>>;

export function ListRequests():Promise<Array<download.Request>>;

export function PauseRequest(arg1:number,arg2:boolean):Promise<void>;

export function Pick(arg1:string,arg2:string):Promise<void>;

export function ProviderKinds():Promise<Array<download.Descriptor>>;

export function ReconcileRequests():Promise<download.Summary>;

export function RemoveRequest(arg1:number):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetPreferences(arg1:download.AutoDownloadPrefs):Promise<void>;

export function SetReconciler(arg1:download.Reconciler):Promise<void>;

export function StartDownload(arg1:download.SearchRequest):Promise<download.StartResult>;

export function TestProvider(arg1:number):Promise<void>;

export function UpdateProvider(arg1:number,arg2:string,arg3:boolean,arg4:number,arg5:Record<string, string>):Promise<void>;
