// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProvider(arg1, arg2, arg3) {
  return window['go']['download']['Service']['AddProvider'](arg1, arg2, arg3);
}

export function AddRequest(arg1) {
  return window['go']['download']['Service']['AddRequest'](arg1);
}

export function Cancel(arg1) {
  return window['go']['download']['Service']['Cancel'](arg1);
}

export function Candidates(arg1) {
  return window['go']['download']['Service']['Candidates'](arg1);
}

export function ClearFinished() {
  return window['go']['download']['Service']['ClearFinished']();
}

export function ClearSatisfiedRequests() {
  return window['go']['download']['Service']['ClearSatisfiedRequests']();
}

export function DeleteProvider(arg1) {
  return window['go']['download']['Service']['DeleteProvider'](arg1);
}

export function ImportExternalRequests(arg1, arg2) {
  return window['go']['download']['Service']['ImportExternalRequests'](arg1, arg2);
}

export function IsRequested(arg1, arg2) {
  return window['go']['download']['Service']['IsRequested'](arg1, arg2);
}

export function ListDownloads(arg1) {
  return window['go']['download']['Service']['ListDownloads'](arg1);
}

export function ListProviders() {
  return window['go']['download']['Service']['ListProviders']();
}

export function ListRequests() {
  return window['go']['download']['Service']['ListRequests']();
}

export function PauseRequest(arg1, arg2) {
  return window['go']['download']['Service']['PauseRequest'](arg1, arg2);
}

export function Pick(arg1, arg2) {
  return window['go']['download']['Service']['Pick'](arg1, arg2);
}

export function ProviderKinds() {
  return window['go']['download']['Service']['ProviderKinds']();
}

export function ReconcileRequests() {
  return window['go']['download']['Service']['ReconcileRequests']();
}

export function RemoveRequest(arg1) {
  return window['go']['download']['Service']['RemoveRequest'](arg1);
}

export function SetContext(arg1) {
  return window['go']['download']['Service']['SetContext'](arg1);
}

export function SetPreferences(arg1) {
  return window['go']['download']['Service']['SetPreferences'](arg1);
}

export function SetReconciler(arg1) {
  return window['go']['download']['Service']['SetReconciler'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['download']['Service']['StartDownload'](arg1);
}

export function TestProvider(arg1) {
  return window['go']['download']['Service']['TestProvider'](arg1);
}

export function UpdateProvider(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['download']['Service']['UpdateProvider'](arg1, arg2, arg3, arg4, arg5);
}
