// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DirectoryPicker() {
  return window['go']['frontendutil']['FrontendUtil']['DirectoryPicker']();
}

export function SetContext(arg1) {
  return window['go']['frontendutil']['FrontendUtil']['SetContext'](arg1);
}
