// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function DirectoryPicker():Promise<string>;

export function ImageFilePicker():Promise<string>;

export function PlaylistFilePicker():Promise<Array<string>>;

export function ReadFile(arg1:string):Promise<Array<number>>;

export function SetContext(arg1:context.Context):Promise<void>;
