// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Library {
    "ID": number;
    "Name": string;
    "Path": string;
    "CreatedAt": string;
    "AutotagWarningAcked": number;
}
