// Code generated by genevents from backend/events/events.go. DO NOT EDIT.

export const Events = {
    // Playback events (backend → frontend push)
    PlaybackStateChanged: "PlaybackStateChanged",
    PlaybackFinished: "PlaybackFinished",
    TrackChanged: "TrackChanged",
    SeekFailed: "SeekFailed",
    VolumeChanged: "VolumeChanged",

    // Queue events (backend → frontend push)
    QueueChanged: "QueueChanged",
    QueueIndexChanged: "QueueIndexChanged",
    QueueModeChanged: "QueueModeChanged",
    QueueTracksModified: "QueueTracksModified",

    // Config events
    LibraryConfigChanged: "LibraryConfigChanged",
    ThemeConfigChanged: "ThemeConfigChanged",
    TrackListConfigChanged: "TrackListConfigChanged",
    FavoritesConfigChanged: "FavoritesConfigChanged",
    ShortcutsConfigChanged: "ShortcutsConfigChanged",

    // Playlist events
    PlaylistCreated: "PlaylistCreated",
    PlaylistDeleted: "PlaylistDeleted",
    PlaylistRenamed: "PlaylistRenamed",
    PlaylistTracksChanged: "PlaylistTracksChanged",
    PlaylistsRestored: "PlaylistsRestored",
    DefaultPlaylistChanged: "DefaultPlaylistChanged",

    // Library events
    LibraryScanStarted: "LibraryScanStarted",
    LibraryScanProgress: "LibraryScanProgress",
    LibraryScanComplete: "LibraryScanComplete",

    // Scan control events
    LibraryScanCancelled: "LibraryScanCancelled",
    LibraryScanPaused: "LibraryScanPaused",
    LibraryScanResumed: "LibraryScanResumed",

    // Scan queue events
    LibraryScanQueued: "LibraryScanQueued",
    LibraryScanQueueDrained: "LibraryScanQueueDrained",

    // Library CRUD events
    LibraryAdded: "LibraryAdded",
    LibraryRenamed: "LibraryRenamed",
    LibraryRemoved: "LibraryRemoved",
} as const;

export type EventName = (typeof Events)[keyof typeof Events];
