// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FrontendUtil provides frontend-bound Go functions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * DirectoryPicker opens a directory selection dialog.
 * 
 * v3 has no separate directory dialog: it is the file dialog told to
 * choose directories and not files.
 */
export function DirectoryPicker(): $CancellablePromise<string> {
    return $Call.ByID(3245034282);
}

/**
 * ImageFilePicker opens a file selection dialog filtered to image
 * files (JPEG, PNG).  Returns the selected file path, or empty
 * string if the user cancelled.
 */
export function ImageFilePicker(): $CancellablePromise<string> {
    return $Call.ByID(3408786006);
}

/**
 * PlaylistFilePicker opens a file selection dialog filtered
 * to M3U/M3U8 playlist files. Multiple files may be selected.
 */
export function PlaylistFilePicker(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2858498591);
}

/**
 * ReadFile reads a file from disk and returns its contents.
 * Used by the frontend to read cover art image files selected
 * via ImageFilePicker.
 */
export function ReadFile(path: string): $CancellablePromise<string | null> {
    return $Call.ByID(3350710867, path);
}
