// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DirEntry is one selectable directory in a listing.
 */
export interface DirEntry {
    "name": string;
    "path": string;
}

/**
 * DirListing is one level of the filesystem, as a folder picker needs
 * it: where we are, what is above, and the directories below.
 * 
 * Parent is empty at a root, which is what tells the UI not to draw an
 * "up" affordance rather than having it compute that from the path
 * separator.
 */
export interface DirListing {
    "path": string;
    "parent": string;
    "entries": DirEntry[] | null;
}

/**
 * StorageAccess reports whether the app can actually read the place the
 * user's music lives.
 */
export interface StorageAccess {
    "root": string;
    "readable": boolean;
    "reason": string;
}
