// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Column represents a visible column in the track list.
 */
export interface Column {
    "id": ColumnID;
}

/**
 * ColumnID identifies a displayable column in the track list.
 */
export enum ColumnID {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Valid column identifiers.
     */
    ColTrackName = "trackName",
    ColArtistName = "artistName",
    ColTrackLength = "trackLength",
    ColAlbum = "album",
    ColGenre = "genre",
    ColYear = "year",
    ColComposer = "composer",
    ColTrackNumber = "trackNumber",
    ColDiscNumber = "discNumber",
    ColFilePath = "filePath",
    ColFileType = "fileType",
    ColSampleRate = "sampleRate",
    ColBitDepth = "bitDepth",
    ColChannels = "channels",
    ColBitrate = "bitrate",
    ColFileSize = "fileSize",
    ColPlayCount = "playCount",
    ColAlbumArt = "albumArt",
};
