// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {autotagservice} from '../models';
import {context} from '../models';
import {jobs} from '../models';

export function AckLibraryWarning(arg1:number):Promise<void>;

export function Apply(arg1:string,arg2:string):Promise<autotagservice.ApplyResultView>;

export function ApplyAsync(arg1:string,arg2:string):Promise<void>;

export function ClearCompletedEntries(arg1:number):Promise<void>;

export function GetCandidateCoverArt(arg1:string,arg2:string):Promise<string>;

export function GetCandidates(arg1:string):Promise<autotagservice.ScoreView>;

export function GetCandidatesForPasteURL(arg1:string,arg2:string):Promise<autotagservice.ScoreView>;

export function GetLocalCoverArt(arg1:string):Promise<string>;

export function GetNextPending():Promise<autotagservice.PendingItem>;

export function GetPendingFolder(arg1:string):Promise<autotagservice.PendingItem>;

export function LeaveAsIs(arg1:string):Promise<void>;

export function ListPendingFolders(arg1:number):Promise<Array<autotagservice.PendingItem>>;

export function RetagGroup(arg1:string):Promise<void>;

export function SearchCandidates(arg1:string,arg2:string,arg3:string):Promise<Array<autotagservice.SearchHitView>>;

export function SelectSearchCandidate(arg1:string,arg2:string,arg3:string):Promise<autotagservice.ScoreView>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetJobRegistry(arg1:jobs.Registry):Promise<void>;

export function Skip(arg1:string):Promise<void>;

export function SplitMixedFolder(arg1:string):Promise<Array<autotagservice.PendingItem>>;

export function StartAutotagQueue(arg1:number):Promise<void>;

export function StartBackgroundPrefetch():Promise<void>;

export function WritesInFlight():Promise<boolean>;
