// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AckLibraryWarning(arg1) {
  return window['go']['autotagservice']['Service']['AckLibraryWarning'](arg1);
}

export function Apply(arg1, arg2) {
  return window['go']['autotagservice']['Service']['Apply'](arg1, arg2);
}

export function ApplyAsync(arg1, arg2) {
  return window['go']['autotagservice']['Service']['ApplyAsync'](arg1, arg2);
}

export function ClearCompletedEntries(arg1) {
  return window['go']['autotagservice']['Service']['ClearCompletedEntries'](arg1);
}

export function GetCandidateCoverArt(arg1, arg2) {
  return window['go']['autotagservice']['Service']['GetCandidateCoverArt'](arg1, arg2);
}

export function GetCandidates(arg1) {
  return window['go']['autotagservice']['Service']['GetCandidates'](arg1);
}

export function GetCandidatesForPasteURL(arg1, arg2) {
  return window['go']['autotagservice']['Service']['GetCandidatesForPasteURL'](arg1, arg2);
}

export function GetLocalCoverArt(arg1) {
  return window['go']['autotagservice']['Service']['GetLocalCoverArt'](arg1);
}

export function GetNextPending() {
  return window['go']['autotagservice']['Service']['GetNextPending']();
}

export function GetPendingFolder(arg1) {
  return window['go']['autotagservice']['Service']['GetPendingFolder'](arg1);
}

export function LeaveAsIs(arg1) {
  return window['go']['autotagservice']['Service']['LeaveAsIs'](arg1);
}

export function ListPendingFolders(arg1) {
  return window['go']['autotagservice']['Service']['ListPendingFolders'](arg1);
}

export function RetagGroup(arg1) {
  return window['go']['autotagservice']['Service']['RetagGroup'](arg1);
}

export function SearchCandidates(arg1, arg2, arg3) {
  return window['go']['autotagservice']['Service']['SearchCandidates'](arg1, arg2, arg3);
}

export function SelectSearchCandidate(arg1, arg2, arg3) {
  return window['go']['autotagservice']['Service']['SelectSearchCandidate'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['autotagservice']['Service']['SetContext'](arg1);
}

export function Skip(arg1) {
  return window['go']['autotagservice']['Service']['Skip'](arg1);
}

export function StartAutotagQueue(arg1) {
  return window['go']['autotagservice']['Service']['StartAutotagQueue'](arg1);
}

export function StartBackgroundPrefetch() {
  return window['go']['autotagservice']['Service']['StartBackgroundPrefetch']();
}
